workspace '../../ShopGunSDK.xcworkspace'
project "CocoapodsDemo"
platform :ios, '10.0'

target 'CocoapodsDemo' do
  use_frameworks!

  # In your actual project you would not use the path-based pod.
  # Instead, something like `pod "ShopGunSDK"``
  # You can also specify subspecs if you only want to use a subsection of the functionality.
  # For example `pod "ShopGunSDK/PagedPublicationView"`
  pod 'ShopGunSDK', :path => '../../'

  # You do not need to do this in your Podfile... this is simply to allow use to build against the latest build of Incito without having to publish a new pod version each time.  
  pod 'Incito', :path => '../../External/incito-ios'
end
